# Generated by Django 2.0.6 on 2018-07-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'verbose_name': '合同', 'verbose_name_plural': '合同'},
        ),
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={'verbose_name': '学员缴费记录', 'verbose_name_plural': '学员缴费记录'},
        ),
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'verbose_name': '学员报名表', 'verbose_name_plural': '学员报名表'},
        ),
    ]
