# Generated by Django 2.0.6 on 2018-07-10 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180708_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='id_num',
            field=models.CharField(default=451258476526541, max_length=128, verbose_name='身份证号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='class_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.ClassList', verbose_name='报名班级'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.UserProfile', verbose_name='课程顾问'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='contract_signed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='客户提交时间'),
        ),
    ]
