# Generated by Django 2.0.6 on 2018-07-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20180710_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='amount',
            field=models.IntegerField(default=500, verbose_name='缴纳金额'),
        ),
    ]
