# Generated by Django 2.0.6 on 2018-07-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180712_1449'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studyrecord',
            unique_together={('students', 'course_record')},
        ),
    ]
