# Generated by Django 2.0.6 on 2018-07-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_userprofile_stu_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyrecord',
            old_name='students',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='note',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='成绩备注'),
        ),
        migrations.AlterUniqueTogether(
            name='studyrecord',
            unique_together={('student', 'course_record')},
        ),
    ]
