# Generated by Django 2.0.6 on 2018-07-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20180719_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm_app_index', '可以查看profect home 下的所有数据库表'), ('crm_crm_index', '可以查看CRM APP里所有数据库表'), ('crm_table_list', '可以查看kingadmin每张表里所有的数据'), ('crm_table_list_view', '可以访问kingadmin表里每条数据的修改页'), ('crm_table_list_change', '可以对kingadmin表里的每条数据进行修改'), ('crm_table_delete', '可以对kingadmin表里的每条数据进行删除'), ('crm_table_obj_add_view', '可以访问kingadmin每张表的数据增加页'), ('crm_table_obj_add', '可以对kingadmin每张表进行数据添加'), ('student_study_homework_details', '可以查看学生作业详情'))},
        ),
    ]
